name: Terraform Plan

on:
  pull_request:
    paths:
      - './terraform/**'
      - '.github/workflows/terraform-plan.yml'

env:
  CONFIG_DIRECTORY: ./terraform
  TF_VERSION: 1.12.1
  VAR_FILE: terraform.tfvars.development
  AWS_REGION: us-east-1
  S3_KEY: frontend-assets

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Init with S3 Backend
      uses: mleager/tf-shared-actions/.github/actions/terraform-init@main
      with:
        bucket: ${{ secrets.STATE_BUCKET }}
        key: ${{ env.S3_KEY }}/terraform.tfstate
        region: ${{ env.AWS_REGION }}

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan (Binary)
      run: terraform plan -var-file=${{ env.VAR_FILE }} -out=tfplan

    - name: Terraform Show (Readable Plan to plan.txt)
      run: terraform show -no-color tfplan | tee plan.txt

    - name: Post Terraform Plan as PR Comment
      if: success()
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const planOutput = require('fs').readFileSync('./terraform/plan.txt', 'utf8');

          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `## Terraform Plan

            <details><summary>Show Plan</summary>

            \`\`\`hcl
            ${planOutput}
            \`\`\`

            </details>`
          });

