name: Terraform Apply

on:
  push:
    branches:
      - main

env:
  CONFIG_DIRECTORY: ./terraform
  TF_VERSION: 1.12.1
  VAR_FILE: terraform.tfvars.development
  AWS_REGION: us-east-1
  S3_KEY: frontend-assets

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Init with S3 Backend
      uses: mleager/tf-shared-actions/.github/actions/terraform-init@main
      with:
        bucket: ${{ secrets.STATE_BUCKET }}
        key: ${{ env.S3_KEY }}/terraform.tfstate
        region: ${{ env.AWS_REGION }}

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan (Binary)
      run: terraform plan -var-file=${{ env.VAR_FILE }} -out=tfplan

    - name: Terraform Show (Readable Plan to plan.txt)
      run: terraform show -no-color tfplan | tee plan.txt

    - name: Terraform Apply
      id: apply
      run: |
        terraform apply -auto-approve tfplan | tee apply_output.txt
        exit_code=${PIPESTATUS[0]}
        echo "exit_code=$exit_code" >> $GITHUB_OUTPUT

    - name: Check Terraform Apply Status
      if: steps.apply.outputs.exit_code != 0
      run: exit 1

    - name: Post Terraform Apply Commit Comment
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const applyOutput = fs.readFileSync('./terraform/apply_output.txt', 'utf8');
          const exitCode = Number(process.env.EXIT_CODE);
          const status = exitCode === 0 ? '✅ Success' : '❌ Failure';

          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: `## Terraform Apply ${status}

            <details><summary>Show Output</summary>

            \`\`\`
            ${applyOutput}
            \`\`\`

            </details>`
          });
      env:
        EXIT_CODE: ${{ steps.apply.outputs.exit_code }}

